
from GlobalVariable import GlobalVariable
from Services.GreetingService import GreetingService
from Services.SpeechRecognitionService import SpeechRecognitionService
from Services.SpeechService import SpeechService
from Services.TaskService import TaskService
from Tasks.SystemTask import SystemTask